services:
  django:
    build:
      context: ./devops/
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        USERNAME: ${USER:-kainga}
    container_name: django-container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-name-net

networks:
  app-name-net:
    driver: bridge
